// flow-typed signature: 2c319ab416ef5407945422c9caede1b1
// flow-typed version: <<STUB>>/extendable-error-class_v^0.1.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extendable-error-class'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'extendable-error-class' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
declare module 'extendable-error-class/dist/index.es5' {
  declare module.exports: any;
}
declare module 'extendable-error-class/index.es2015' {
  declare module.exports: any;

  // Filename aliases
}
declare module 'extendable-error-class/dist/index.es5.js' {
  declare module.exports: $Exports<'extendable-error-class/dist/index.es5'>;
}
declare module 'extendable-error-class/index.es2015.js' {
  declare module.exports: $Exports<'extendable-error-class/index.es2015'>;
}
