// flow-typed signature: 15f1a8b736e2c6eb37a3e3823d588441
// flow-typed version: <<STUB>>/jest-codemods_v^0.10.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-codemods'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-codemods' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
declare module 'jest-codemods/bin/jest-codemods' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/cli/git-status' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/cli/index' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/cli/transformers' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/transformers/ava' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/transformers/chai-assert' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/transformers/chai-should' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/transformers/mocha' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/transformers/should' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/transformers/tape' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/chai-chain-utils' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/consts' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/imports' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/incompatible-packages' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/logger' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/proxyquire' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/quote-style' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/recast-helpers' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/tape-ava-helpers' {
  declare module.exports: any;
}
declare module 'jest-codemods/dist/utils/test-helpers' {
  declare module.exports: any;

  // Filename aliases
}
declare module 'jest-codemods/bin/jest-codemods.js' {
  declare module.exports: $Exports<'jest-codemods/bin/jest-codemods'>;
}
declare module 'jest-codemods/dist/cli/git-status.js' {
  declare module.exports: $Exports<'jest-codemods/dist/cli/git-status'>;
}
declare module 'jest-codemods/dist/cli/index.js' {
  declare module.exports: $Exports<'jest-codemods/dist/cli/index'>;
}
declare module 'jest-codemods/dist/cli/transformers.js' {
  declare module.exports: $Exports<'jest-codemods/dist/cli/transformers'>;
}
declare module 'jest-codemods/dist/transformers/ava.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/ava'>;
}
declare module 'jest-codemods/dist/transformers/chai-assert.js' {
  declare module.exports: $Exports<
    'jest-codemods/dist/transformers/chai-assert'
  >;
}
declare module 'jest-codemods/dist/transformers/chai-should.js' {
  declare module.exports: $Exports<
    'jest-codemods/dist/transformers/chai-should'
  >;
}
declare module 'jest-codemods/dist/transformers/mocha.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/mocha'>;
}
declare module 'jest-codemods/dist/transformers/should.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/should'>;
}
declare module 'jest-codemods/dist/transformers/tape.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/tape'>;
}
declare module 'jest-codemods/dist/utils/chai-chain-utils.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/chai-chain-utils'>;
}
declare module 'jest-codemods/dist/utils/consts.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/consts'>;
}
declare module 'jest-codemods/dist/utils/imports.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/imports'>;
}
declare module 'jest-codemods/dist/utils/incompatible-packages.js' {
  declare module.exports: $Exports<
    'jest-codemods/dist/utils/incompatible-packages'
  >;
}
declare module 'jest-codemods/dist/utils/logger.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/logger'>;
}
declare module 'jest-codemods/dist/utils/proxyquire.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/proxyquire'>;
}
declare module 'jest-codemods/dist/utils/quote-style.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/quote-style'>;
}
declare module 'jest-codemods/dist/utils/recast-helpers.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/recast-helpers'>;
}
declare module 'jest-codemods/dist/utils/tape-ava-helpers.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/tape-ava-helpers'>;
}
declare module 'jest-codemods/dist/utils/test-helpers.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/test-helpers'>;
}
