// flow-typed signature: 7a845ea9cd546f9eea9da9250f24e954
// flow-typed version: <<STUB>>/pegjs-loader_v^0.5.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pegjs-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pegjs-loader' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
declare module 'pegjs-loader/lib/index' {
  declare module.exports: any;
}
declare module 'pegjs-loader/src/index' {
  declare module.exports: any;

  // Filename aliases
}
declare module 'pegjs-loader/lib/index.js' {
  declare module.exports: $Exports<'pegjs-loader/lib/index'>;
}
declare module 'pegjs-loader/src/index.js' {
  declare module.exports: $Exports<'pegjs-loader/src/index'>;
}
