// flow-typed signature: 04f8aa276ca7c73ba6b2d0e20754cca3
// flow-typed version: <<STUB>>/pug-loader_v^2.3.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-loader/stringify.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-loader/index' {
  declare module.exports: $Exports<'pug-loader'>;
}
declare module 'pug-loader/index.js' {
  declare module.exports: $Exports<'pug-loader'>;
}
declare module 'pug-loader/stringify.loader.js' {
  declare module.exports: $Exports<'pug-loader/stringify.loader'>;
}
