// flow-typed signature: 84b44894beaa5d35908e5967538e769c
// flow-typed version: <<STUB>>/webpack-stats-plugin_v^0.1.4/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-stats-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-stats-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-stats-plugin/demo/main' {
  declare module.exports: any;
}

declare module 'webpack-stats-plugin/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-stats-plugin/gulpfile' {
  declare module.exports: any;
}

declare module 'webpack-stats-plugin/lib/stats-writer-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-stats-plugin/demo/main.js' {
  declare module.exports: $Exports<'webpack-stats-plugin/demo/main'>;
}
declare module 'webpack-stats-plugin/demo/webpack.config.js' {
  declare module.exports: $Exports<'webpack-stats-plugin/demo/webpack.config'>;
}
declare module 'webpack-stats-plugin/gulpfile.js' {
  declare module.exports: $Exports<'webpack-stats-plugin/gulpfile'>;
}
declare module 'webpack-stats-plugin/index' {
  declare module.exports: $Exports<'webpack-stats-plugin'>;
}
declare module 'webpack-stats-plugin/index.js' {
  declare module.exports: $Exports<'webpack-stats-plugin'>;
}
declare module 'webpack-stats-plugin/lib/stats-writer-plugin.js' {
  declare module.exports: $Exports<'webpack-stats-plugin/lib/stats-writer-plugin'>;
}
