// flow-typed signature: 341dba02e491fae9f3b0c39eece8ed9a
// flow-typed version: <<STUB>>/webpack-merge_v^0.17.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-merge/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/join-arrays' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/kernel' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/reduce-loaders' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/utils' {
  declare module.exports: any;
}

declare module 'webpack-merge/src/index' {
  declare module.exports: any;
}

declare module 'webpack-merge/src/join-arrays' {
  declare module.exports: any;
}

declare module 'webpack-merge/src/reduce-loaders' {
  declare module.exports: any;
}

declare module 'webpack-merge/tests/merge-tests' {
  declare module.exports: any;
}

declare module 'webpack-merge/tests/test-merge-smart' {
  declare module.exports: any;
}

declare module 'webpack-merge/tests/test-merge-strategy' {
  declare module.exports: any;
}

declare module 'webpack-merge/tests/test-merge' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-merge/lib/index.js' {
  declare module.exports: $Exports<'webpack-merge/lib/index'>;
}
declare module 'webpack-merge/lib/join-arrays.js' {
  declare module.exports: $Exports<'webpack-merge/lib/join-arrays'>;
}
declare module 'webpack-merge/lib/kernel.js' {
  declare module.exports: $Exports<'webpack-merge/lib/kernel'>;
}
declare module 'webpack-merge/lib/reduce-loaders.js' {
  declare module.exports: $Exports<'webpack-merge/lib/reduce-loaders'>;
}
declare module 'webpack-merge/lib/utils.js' {
  declare module.exports: $Exports<'webpack-merge/lib/utils'>;
}
declare module 'webpack-merge/src/index.js' {
  declare module.exports: $Exports<'webpack-merge/src/index'>;
}
declare module 'webpack-merge/src/join-arrays.js' {
  declare module.exports: $Exports<'webpack-merge/src/join-arrays'>;
}
declare module 'webpack-merge/src/reduce-loaders.js' {
  declare module.exports: $Exports<'webpack-merge/src/reduce-loaders'>;
}
declare module 'webpack-merge/tests/merge-tests.js' {
  declare module.exports: $Exports<'webpack-merge/tests/merge-tests'>;
}
declare module 'webpack-merge/tests/test-merge-smart.js' {
  declare module.exports: $Exports<'webpack-merge/tests/test-merge-smart'>;
}
declare module 'webpack-merge/tests/test-merge-strategy.js' {
  declare module.exports: $Exports<'webpack-merge/tests/test-merge-strategy'>;
}
declare module 'webpack-merge/tests/test-merge.js' {
  declare module.exports: $Exports<'webpack-merge/tests/test-merge'>;
}
